### PR TITLE
Lw/7770 new headline

### PR DESCRIPTION
**Pull request by johnnieskywalker**
# [New Vault headline](https://app.shortcut.com/oazo-apps/story/7770/implement-new-version-of-vault-headline)

## Changes 👷‍♀️
- Implemented new headline according to design https://www.figma.com/file/XeMo7s0ZJgXgCHmOd588QY/Discover-Oasis-%235366?node-id=2904%3A16028  
  
## How to test 🧪
- Check vault headlines in various vaults in various states see if everything fits, no layout is broken, here are some examples:

image

image

image

image
This branch is started from dev so it doesn't yet have validations, but I  just can simulate edge caser that was found by @piotrkonowrocki 
image

Let's say hypotheticaly in one of languages we support message will be even longer still looks fine

image
image

AAVE
image

### CODE REVIEW

**Comment by johnnieskywalker** [comment]
https://user-images.githubusercontent.com/6871923/215856025-bdbe5bc1-1224-4da6-8441-1bfdee456520.mp4

**Comment by johnnieskywalker** [comment]
image

**Review by adamskrodzki — DISMISSED** [review]
Tested, looks ok.

**Comment by johnnieskywalker** [comment]
Will try to achieve the same thing but using flex boxes to make 2 rows only when there's too much details

**Comment by johnnieskywalker** [comment]
@adamskrodzki @piotrkonowrocki before changes I'm about to push:
image
image

after recent changes:
image

ETH-C remains the same
image

**Comment by johnnieskywalker** [comment]
This approach is wrong

**Pull request closed without merging**
