### PR TITLE
Close modal window only when you click outside of it and not inside.

### PR DESCRIPTION
**Pull request by peculiarity**
https://www.notion.so/oazo/Multiply-MVP-tests-Feedback-bugs-2a776db8d0cf4acdb42717c96ccdf9d2#b0d8445e1ac34e2197147c5154cab5d2

The modal windows `MUST BE` closed:
 - Clicking outside the modal container itself
 - Pressing `ESC` button
 - Clicking `close` button in the top right corner.
 
 The modal windows `MUST NOT BE` closed:
 - Click inside on any part of the modal itself.

Modals to test:
 - `Error`
 - `Account`
 - `Selecting Vault Type`
 - `Signing ToS`

### CODE REVIEW

**Comment by johnnieskywalker** [comment]
Know the issue. Tested on error modal, where it was mostly annoying form me when copying the bug. Now I can easily copy the stacktrace or part of it intuitively.

image

image

**Review by johnnieskywalker — APPROVED** [review]

**Comment by johnnieskywalker** [comment]
This works and closes as expected
image

TOS doesn't have close button but it has close function and new error modal will be like that too
image

and when it is clicked outside it crashes like that
image

**Review by johnnieskywalker — CHANGES_REQUESTED** [review]
TOS doesn't have close button but it has close function and new error modal will be like that too
image

and when it is clicked outside it crashes like that
image

**Comment by johnnieskywalker** [comment]
TOS after last changes

clicking modal doesnt close it I can easily also copy text - :heavy_check_mark: super
image

Clicking outside modeal triggers function that is called also when clicking disconnect. This makes sense, because before it was just closing the popup and leaving blurred page so one could look at it but don't do any actions unless refreshed to connect wallet again

but when I did it twice then modal doesn't close, it remains on top of screen

**Review by adamskrodzki — APPROVED** [review]
Tested and working

**Review by johnnieskywalker — CHANGES_REQUESTED** [review]
When you go to see TOS directly using URL `https://localhost:3443/vaults/open-multiply/ETH-A?network=hardhat` TOS popup is not closing nor triggering disconnect button action when clicking outside modal

**Comment by adamskrodzki** [comment]
Temporarily closing since there are some doubts and It is not urgent, let's reopen after the launch

**Review by johnnieskywalker — APPROVED** [review]

**Pull request merged**
