### PR TITLE
ENS support

### LINKED ISSUE #664: Show ENS name and avatar in UI if user owned one
**Is your feature request related to a problem? Please describe.**
It would be great if we show the ENS name and avatar if the user has it

**Describe the solution you'd like**
We just gonna replace the address with ens name

**Describe alternatives you've considered**
Using ethers, we can able to resolve the ENS domain and avatar of the address.

**Additional context**
image
image

### PR DESCRIPTION
**Pull request by sasicodes**
Added ENS name and avatar support if user-owned one. Closes #664

image
image

## Changes 👷‍♀️
- Create a variable in accountData$ called `ensName` and 
- Used the JsonRpcProvider from `context$`
  
## How to test 🧪
  Connect account that has mapped with ENS domains

### CODE REVIEW

**Comment by sasicodes** [comment]
cc @adamskrodzki

**Comment by bigint** [comment]
@sasicodes there is already a PR waiting for review, they closed it because of holidays 

https://github.com/OasisDEX/oasis-borrow/pull/677#issuecomment-998660915

**Comment by rkrasiuk** [comment]
@sasicodes well done! apologies for the delay in reviewing this PR. We would need just two things to be fixed to get this merged in 
1. davatar also accepts the [optional provider](https://github.com/metaphor-xyz/davatar-helpers/blob/5cdeae29f863c1e8043ee86e1c1cf93b2f0c0ab5/packages/react/src/index.tsx#L12), make sure to pass that in 
2. the conflicts with the target branch. they are mundane, so should be quick to fix

**Comment by sasicodes** [comment]
@rkrasiuk  Updated provider in Davatar

**Comment by rkrasiuk** [comment]
@sasicodes appreciate you addressing this so soon. i will test it once more shortly

**Review by rkrasiuk — APPROVED** [review]

**Pull request merged**
