### PR TITLE
new share icon

### PR DESCRIPTION
**Pull request by johnnieskywalker**
# [New Share icon](https://app.shortcut.com/oazo-apps/story/7784/update-the-share-vaults-icon)
  
## Changes 👷‍♀️
- Changed share icon, also corrected some CSS details to make it fit 
  
## How to test 🧪
- Check on discovery page 
image

- Check on VaultOverview page 
image

- Also check AAVE, GUNI, DSR
image

### CODE REVIEW

**Comment by Rai-Stone** [comment]
Screenshot 2023-01-31 at 14 46 17

The Icon does not look centred in this screen.

**Comment by johnnieskywalker** [comment]
> Screenshot 2023-01-31 at 14 46 17
> 
> The Icon does not look centred on this screen. Please can you resolve this before merging.

gotcha
image

**Comment by johnnieskywalker** [comment]
G-UNI 
image

**Comment by paszkowskiDamian** [comment]
On the mobile the buttons have different sizes 
image

**Comment by johnnieskywalker** [comment]
Mobile, star to be fixed
image

**Comment by johnnieskywalker** [comment]
mobile discover now different resolutions
image

image

image
image

image

vault overview

image

image

image

image

**Comment by paszkowskiDamian** [comment]
image

They still have different sizes

**Comment by johnnieskywalker** [comment]
https://user-images.githubusercontent.com/6871923/216086738-83a461ee-b3ca-4d33-a998-1fecd07e51cb.mp4

**Comment by johnnieskywalker** [comment]
https://user-images.githubusercontent.com/6871923/216610218-15aedb10-ae4f-4753-8033-65dd8faf52aa.mp4

Discovery broke after merging dev, going to fix and then test one more time

**Comment by johnnieskywalker** [comment]
https://user-images.githubusercontent.com/6871923/216614431-5156a66c-d0b9-4d59-998c-3890e85f5ad9.mp4

**Comment by johnnieskywalker** [comment]
https://user-images.githubusercontent.com/6871923/216617929-90e0667f-73c1-4346-b509-abb0afead889.mp4

last updates

**Comment by johnnieskywalker** [comment]
After adding one more px of margin 
image

image

image

image

image

**Review by piotrkonowrocki — APPROVED** [review]

**Pull request merged**
